# Setup
title:               Radiation Oncology
tagline:             'for patient and doctors'
description:         'A reserved <a href="https://pubmed.ncbi.nlm.nih.gov/" target="_blank">Jekyll</a> Made by <a href="https://twitter.com/KBerthelot_MD" target="_blank">@KBerthelot_MD</a>.'
url:                 http://kbot1.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kevin Berthelot
  url:               https://twitter.com/KBerthelot_MD
  email:             kev.berthelot@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
